"""Export reusable player settings as an Archipelago generation smoke YAML."""

from pathlib import Path
import argparse

from Archipelago.yaml_config import serialize_player_yaml
from randomizer.config.player import load_config


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--yaml",
        default="Archipelago/smoke/dta.yaml",
    )
    args = parser.parse_args()
    output = Path(args.yaml)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        serialize_player_yaml(load_config(), "DTAFullSmoke"),
        encoding="utf-8",
        newline="\n",
    )
    print(f"{output}: reusable player settings; run generated by Archipelago")



if __name__ == "__main__":
    main()
